name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'Android/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Android/**'

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission
        run: chmod +x Android/src/gradlew

      - name: Build APK
        working-directory: Android/src
        run: ./gradlew assembleRelease -PdynamicVersionCode=${{ github.run_number }} -PdynamicVersionNameSuffix=-PR${{ github.event.pull_request.number || 'main' }}-Run${{ github.run_number }}

      # 🔍 Debug (optional but useful)
      - name: List APK files
        run: find Android -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: Android/src/**/build/outputs/apk/**/*.apk
